-- MySQL Script generated by MySQL Workbench
-- sex 11 dez 2020 15:20:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresaDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresaDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresaDB` DEFAULT CHARACTER SET utf8 ;
USE `empresaDB` ;

-- -----------------------------------------------------
-- Table `empresaDB`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaDB`.`clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `dtNascimento` DATE NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaDB`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaDB`.`tipo` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;

INSERT INTO tipo (idTipo, nome) VALUES (1, "Instalação de equipamento");
INSERT INTO tipo (idTipo, nome) VALUES (2, "Troca de peça");
INSERT INTO tipo (idTipo, nome) VALUES (3, "Manutenção de computadores");
INSERT INTO tipo (idTipo, nome) VALUES (4, "Manutenção de Software");
INSERT INTO tipo (idTipo, nome) VALUES (5, "Manutenção de servidor");
INSERT INTO tipo (idTipo, nome) VALUES (6, "Manutenção de infraestrutura");
INSERT INTO tipo (idTipo, nome) VALUES (7, "Manutenção de redes");


-- -----------------------------------------------------
-- Table `empresaDB`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaDB`.`servicos` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `idTipo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`idServico`),
  INDEX `fk_servicos_tipo_idx` (`idTipo` ASC),
  INDEX `fk_servicos_clientes1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_servicos_tipo`
    FOREIGN KEY (`idTipo`)
    REFERENCES `empresaDB`.`tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_clientes1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `empresaDB`.`clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaDB`.`datasdisponiveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaDB`.`datasdisponiveis` (
  `idDisponibilidade` INT NOT NULL AUTO_INCREMENT,
  `idServico` INT NOT NULL,
  `data` DATE NOT NULL,
  `disponivel` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idDisponibilidade`),
  INDEX `fk_datasdisponiveis_servicos1_idx` (`idServico` ASC),
  CONSTRAINT `fk_datasdisponiveis_servicos1`
    FOREIGN KEY (`idServico`)
    REFERENCES `empresaDB`.`servicos` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaDB`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaDB`.`venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_venda_clientes1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_venda_clientes1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `empresaDB`.`clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresaDB`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresaDB`.`item` (
  `dataContratada` DATE NOT NULL,
  `idVenda` INT NOT NULL,
  `idServico` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`dataContratada`, `idVenda`, `idServico`),
  INDEX `fk_venda_has_servicos_servicos1_idx` (`idServico` ASC),
  INDEX `fk_venda_has_servicos_venda1_idx` (`idVenda` ASC),
  CONSTRAINT `fk_venda_has_servicos_venda1`
    FOREIGN KEY (`idVenda`)
    REFERENCES `empresaDB`.`venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_servicos_servicos1`
    FOREIGN KEY (`idServico`)
    REFERENCES `empresaDB`.`servicos` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
