-- MySQL Script generated by MySQL Workbench
-- dom 06 dez 2020 20:16:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `dtNascimento` DATE NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicos` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `idTipo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`idServico`),
  INDEX `fk_servicos_tipo_idx` (`idTipo` ASC) VISIBLE,
  CONSTRAINT `fk_servicos_tipo`
    FOREIGN KEY (`idTipo`)
    REFERENCES `mydb`.`tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`datasdisponiveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datasdisponiveis` (
  `idDisponibilidade` INT NOT NULL AUTO_INCREMENT,
  `idServico` INT NOT NULL,
  `data` DATE NOT NULL,
  `disponivel` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idDisponibilidade`),
  INDEX `fk_datasdisponiveis_servicos1_idx` (`idServico` ASC) VISIBLE,
  CONSTRAINT `fk_datasdisponiveis_servicos1`
    FOREIGN KEY (`idServico`)
    REFERENCES `mydb`.`servicos` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_venda_clientes1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_venda_clientes1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `idVenda` INT NOT NULL,
  `idServico` INT NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVenda`, `idServico`),
  INDEX `fk_venda_has_servicos_servicos1_idx` (`idServico` ASC) VISIBLE,
  INDEX `fk_venda_has_servicos_venda1_idx` (`idVenda` ASC) VISIBLE,
  CONSTRAINT `fk_venda_has_servicos_venda1`
    FOREIGN KEY (`idVenda`)
    REFERENCES `mydb`.`venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_servicos_servicos1`
    FOREIGN KEY (`idServico`)
    REFERENCES `mydb`.`servicos` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `idAdm` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `autenticacao` INT NOT NULL,
  `senha` INT NOT NULL,
  PRIMARY KEY (`idAdm`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
